# Generated by Django 2.0.6 on 2018-06-27 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interactionscore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectobjective',
            name='hcp',
        ),
        migrations.AddField(
            model_name='projectobjective',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='interactionscore.Project'),
            preserve_default=False,
        ),
    ]
