# Generated by Django 2.0.6 on 2018-06-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactionscore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='affiliate_groups',
            field=models.ManyToManyField(related_name='users', to='interactionscore.AffiliateGroup'),
        ),
    ]
