# Generated by Django 2.0.6 on 2018-06-27 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactionscore', '0002_auto_20180627_0744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engagementplanprojectitem',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='engagementplanprojectitem',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='projectobjective',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='projectobjective',
            name='approved_at',
        ),
    ]
