# Generated by Django 2.0.6 on 2018-06-18 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactionscore', '0003_engagementplan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='engagementplan',
            options={'permissions': (('approve_ep', 'Can approve EPs'),)},
        ),
    ]
