# Generated by Django 2.0.6 on 2018-06-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactionscore', '0003_auto_20180627_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interaction',
            old_name='appropriate_procedures_followed',
            new_name='appropriate_pv_procedures_followed',
        ),
        migrations.AddField(
            model_name='interaction',
            name='type_of_interaction',
            field=models.CharField(choices=[('phone', 'Phone'), ('face_to_face', 'Face-to-face'), ('other', 'Email')], default='face_to_face', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interaction',
            name='origin_of_interaction',
            field=models.CharField(choices=[('medinfo_enquiry', 'MedInfo enquiry'), ('engagement_plan', 'Engagement Plan'), ('other', 'Other')], max_length=255),
        ),
    ]
