# Generated by Django 2.0.6 on 2018-07-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactionscore', '0004_auto_20180628_0927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='therapeuticarea',
            name='resources',
        ),
        migrations.AddField(
            model_name='hcp',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='hcp',
            name='country',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='hcp',
            name='phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='hcp',
            name='time_availability',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='affiliate_groups',
            field=models.ManyToManyField(blank=True, related_name='projects', to='interactionscore.AffiliateGroup'),
        ),
        migrations.AddField(
            model_name='project',
            name='tas',
            field=models.ManyToManyField(blank=True, related_name='projects', to='interactionscore.TherapeuticArea'),
        ),
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('personal_project', 'Personal'), ('country_project', 'Country'), ('global_project', 'Global')], default='global_project', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='affiliate_groups',
            field=models.ManyToManyField(blank=True, related_name='resources', to='interactionscore.AffiliateGroup'),
        ),
        migrations.AddField(
            model_name='resource',
            name='description',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='tas',
            field=models.ManyToManyField(blank=True, related_name='resources', to='interactionscore.TherapeuticArea'),
        ),
        migrations.AddField(
            model_name='resource',
            name='title',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='zinc_number_country',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='zinc_number_global',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
