# Generated by Django 2.0.6 on 2018-06-18 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactionscore', '0005_auto_20180618_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='affiliate_groups',
            field=models.ManyToManyField(blank=True, related_name='users', to='interactionscore.AffiliateGroup'),
        ),
    ]
