# Generated by Django 2.0.6 on 2018-07-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactionscore', '0005_auto_20180702_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='hcp',
            name='contact_person_email',
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='hcp',
            name='contact_person_first_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='hcp',
            name='contact_person_last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='hcp',
            name='contact_person_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
