# Generated by Django 2.0.6 on 2018-06-18 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactionscore', '0006_auto_20180618_1015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='engagementplan',
            options={'permissions': [('list_all_ep', 'Can list all EPs'), ('list_own_ag_ep', 'Can list EPs of own AGs'), ('change_own_current_ep', 'Can change own current EP'), ('approve_all_ep', 'Can approve all EPs')]},
        ),
    ]
