# Generated by Django 2.0.6 on 2018-07-02 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactionscore', '0007_auto_20180702_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engagementplan',
            name='year',
        ),
    ]
