# Generated by Django 2.0.6 on 2018-06-18 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactionscore', '0008_auto_20180618_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagementplan',
            name='year',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
