# Generated by Django 2.0.6 on 2018-06-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactionscore', '0010_auto_20180618_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business_title',
            field=models.CharField(blank=True, help_text='Business position title, eg. "Medical Manager"', max_length=255),
        ),
    ]
