# Generated by Django 2.0.6 on 2018-06-19 07:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactionscore', '0011_user_business_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagementplan',
            name='year',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
