# Generated by Django 2.0.6 on 2018-07-09 09:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('interactionscore', '0011_auto_20180702_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interaction',
            name='outcomes',
        ),
        migrations.AddField(
            model_name='interaction',
            name='is_proactive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interaction',
            name='joint_visit_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='interaction',
            name='outcome',
            field=models.CharField(choices=[('follow_up', 'Follow up'), ('no_further_actions', 'No further actions')], default='no_further_actions', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interaction',
            name='time_of_interaction',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interaction',
            name='type_of_interaction',
            field=models.CharField(choices=[('phone', 'Phone'), ('face_to_face', 'Face-to-face'), ('email', 'Email')], max_length=255),
        ),
        migrations.DeleteModel(
            name='InteractionOutcome',
        ),
    ]
