# Generated by Django 2.0.6 on 2018-07-12 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactionscore', '0012_auto_20180709_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='follow_up_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interaction',
            name='follow_up_notes',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
