# Generated by Django 2.0.6 on 2018-07-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactionscore', '0013_auto_20180712_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='hcp',
            name='has_consented',
            field=models.BooleanField(default=False),
        ),
    ]
