# Generated by Django 2.0.6 on 2018-07-17 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactionscore', '0015_auto_20180717_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interaction',
            name='description',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='outcome',
        ),
    ]
