# Generated by Django 2.0.6 on 2018-06-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactionscore', '0015_auto_20180619_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagementlistitem',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='engagementlistitem',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hcpdeliverable',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='hcpobjective',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hcpobjective',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hcpobjective',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hcpdeliverable',
            name='quarter',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Q1'), (2, 'Q2'), (3, 'Q3'), (4, 'Q4')]),
        ),
    ]
