# Generated by Django 2.0.6 on 2018-07-18 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interactionscore', '0016_auto_20180717_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='hcp_objective',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='interactionscore.HCPObjective'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='interactionscore.Project'),
        ),
    ]
