# Generated by Django 2.0.6 on 2018-06-21 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interactionscore', '0017_auto_20180619_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tas',
            field=models.ManyToManyField(blank=True, related_name='users', to='interactionscore.TherapeuticArea'),
        ),
        migrations.AlterField(
            model_name='engagementlistitem',
            name='engagement_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_list_items', to='interactionscore.EngagementPlan'),
        ),
        migrations.AlterField(
            model_name='hcpdeliverable',
            name='hcp_objective',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='interactionscore.HCPObjective'),
        ),
        migrations.AlterField(
            model_name='hcpobjective',
            name='engagement_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hcp_objectives', to='interactionscore.EngagementPlan'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='MSL'),
        ),
    ]
