# Generated by Django 2.0.6 on 2018-07-24 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interactionscore', '0017_auto_20180718_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandCriticalSuccessFactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('affiliate_groups', models.ManyToManyField(blank=True, to='interactionscore.AffiliateGroup')),
                ('ta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='interactionscore.TherapeuticArea')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalPlanObjective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('affiliate_groups', models.ManyToManyField(blank=True, to='interactionscore.AffiliateGroup')),
                ('ta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='interactionscore.TherapeuticArea')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='engagementplanhcpitem',
            name='reason',
            field=models.CharField(choices=[('reason1', 'Reason 1'), ('reason2', 'Reason 2'), ('other', 'Other')], default='other', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engagementplanhcpitem',
            name='reason_other',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
