# Generated by Django 2.0.6 on 2018-06-25 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interactionscore', '0018_auto_20180621_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngagementPlanItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('engagement_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='interactionscore.EngagementPlan')),
                ('hcp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interactionscore.HCP')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='engagementlistitem',
            name='engagement_plan',
        ),
        migrations.RemoveField(
            model_name='engagementlistitem',
            name='hcp',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='engagement_list_item',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='hcp_objective',
        ),
        migrations.RemoveField(
            model_name='hcpobjective',
            name='engagement_plan',
        ),
        migrations.AddField(
            model_name='comment',
            name='engagement_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='interactionscore.EngagementPlan'),
        ),
        migrations.DeleteModel(
            name='EngagementListItem',
        ),
        migrations.AddField(
            model_name='comment',
            name='engagement_plan_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='interactionscore.EngagementPlanItem'),
        ),
        migrations.AddField(
            model_name='hcpobjective',
            name='engagement_plan_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hcp_objectives', to='interactionscore.EngagementPlanItem'),
        ),
    ]
