# Generated by Django 2.0.6 on 2018-07-24 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interactionscore', '0018_auto_20180724_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='hcpobjective',
            name='bcsf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='interactionscore.BrandCriticalSuccessFactor'),
        ),
        migrations.AddField(
            model_name='hcpobjective',
            name='medical_plan_objective',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='interactionscore.MedicalPlanObjective'),
        ),
        migrations.AddField(
            model_name='hcpobjective',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='interactionscore.Project'),
        ),
    ]
