# Generated by Django 2.0.6 on 2018-07-31 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactionscore', '0019_auto_20180724_1529'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hcpdeliverable',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='projectdeliverable',
            unique_together=set(),
        ),
    ]
