# Generated by Django 2.0.6 on 2018-06-25 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interactionscore', '0019_auto_20180625_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hcpobjective',
            name='engagement_plan_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hcp_objectives', to='interactionscore.EngagementPlanItem'),
            preserve_default=False,
        ),
    ]
