# Generated by Django 2.0.6 on 2018-08-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactionscore', '0020_auto_20180731_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagementplanhcpitem',
            name='removed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engagementplanprojectitem',
            name='removed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
