# Generated by Django 2.0.6 on 2018-06-26 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interactionscore', '0020_auto_20180625_0854'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngagementPlanHCPItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EngagementPlanProjectItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectDeliverable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quarter', models.PositiveSmallIntegerField(choices=[(1, 'Q1'), (2, 'Q2'), (3, 'Q3'), (4, 'Q4')])),
                ('description', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(blank=True, choices=[('on_track', 'On Track'), ('slightly_behind', 'Slightly Behind'), ('major_issue', 'Major Issue')], max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectObjective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField()),
                ('engagement_plan_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='interactionscore.EngagementPlanProjectItem')),
                ('hcp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interactionscore.HCP')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='engagementplanitem',
            name='engagement_plan',
        ),
        migrations.RemoveField(
            model_name='engagementplanitem',
            name='hcp',
        ),
        migrations.RenameField(
            model_name='hcpdeliverable',
            old_name='hcp_objective',
            new_name='objective',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='engagement_plan_item',
        ),
        migrations.AlterField(
            model_name='engagementplan',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='engagement_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hcpobjective',
            name='engagement_plan_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='interactionscore.EngagementPlanHCPItem'),
        ),
        migrations.AlterUniqueTogether(
            name='hcpdeliverable',
            unique_together={('quarter', 'objective')},
        ),
        migrations.DeleteModel(
            name='EngagementPlanItem',
        ),
        migrations.AddField(
            model_name='projectdeliverable',
            name='objective',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='interactionscore.ProjectObjective'),
        ),
        migrations.AddField(
            model_name='engagementplanprojectitem',
            name='engagement_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_items', to='interactionscore.EngagementPlan'),
        ),
        migrations.AddField(
            model_name='engagementplanprojectitem',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interactionscore.Project'),
        ),
        migrations.AddField(
            model_name='engagementplanhcpitem',
            name='engagement_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hcp_items', to='interactionscore.EngagementPlan'),
        ),
        migrations.AddField(
            model_name='engagementplanhcpitem',
            name='hcp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interactionscore.HCP'),
        ),
        migrations.AddField(
            model_name='comment',
            name='engagement_plan_hcp_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='interactionscore.EngagementPlanHCPItem'),
        ),
        migrations.AddField(
            model_name='comment',
            name='engagement_plan_project_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='interactionscore.EngagementPlanProjectItem'),
        ),
        migrations.AlterUniqueTogether(
            name='projectdeliverable',
            unique_together={('quarter', 'objective')},
        ),
    ]
