# Generated by Django 2.0.6 on 2018-08-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactionscore', '0021_auto_20180801_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagementplanhcpitem',
            name='reason_removed',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='engagementplanprojectitem',
            name='reason_removed',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
