# Generated by Django 2.0.6 on 2018-08-03 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interactionscore', '0022_auto_20180802_1549'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affiliategroup',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='brandcriticalsuccessfactor',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='engagementplanhcpitem',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='engagementplanprojectitem',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='hcp',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='hcpdeliverable',
            options={'ordering': ['quarter', 'created_at']},
        ),
        migrations.AlterModelOptions(
            name='hcpobjective',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='medicalplanobjective',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='projectdeliverable',
            options={'ordering': ['quarter', 'created_at']},
        ),
        migrations.AlterModelOptions(
            name='projectobjective',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='therapeuticarea',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='comment',
            name='hcp_deliverable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='interactionscore.HCPDeliverable'),
        ),
        migrations.AddField(
            model_name='comment',
            name='hcp_objective',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='interactionscore.HCPObjective'),
        ),
        migrations.AddField(
            model_name='comment',
            name='project_deliverable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='interactionscore.ProjectDeliverable'),
        ),
        migrations.AddField(
            model_name='comment',
            name='project_objective',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='interactionscore.ProjectObjective'),
        ),
    ]
