# Generated by Django 2.0.6 on 2018-08-10 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interactionscore', '0023_auto_20180803_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectobjective',
            name='bcsf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='interactionscore.BrandCriticalSuccessFactor'),
        ),
        migrations.AddField(
            model_name='projectobjective',
            name='medical_plan_objective',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='interactionscore.MedicalPlanObjective'),
        ),
    ]
