# Generated by Django 2.0.6 on 2018-08-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactionscore', '0024_auto_20180810_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='is_joint_visit_manager_approved',
            field=models.BooleanField(default=False, verbose_name='Joint visit approved by Manager'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='joint_visit_reason_other',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='joint_visit_reason',
            field=models.TextField(blank=True, choices=[('option1', 'Option 1'), ('option2', 'Option 2'), ('other', 'Other')]),
        ),
    ]
